name: Feature request
description: Suggest an improvement for PlaylistSeeker releases
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What is painful today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should change?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workaround or alternative behavior
  - type: input
    id: app_version
    attributes:
      label: Current app version
      placeholder: v1.1.0
